"""Generate docs/reference/configuration.md from the Settings model.

Usage (from backend/)::

    python scripts/gen_config_reference.py          # write the file
    python scripts/gen_config_reference.py --check  # exit 1 if the file is out of date (CI and tests)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import get_args

from automl_agent.config import BACKEND_ROOT, REPO_ROOT, Settings

OUTPUT = REPO_ROOT / "docs" / "reference" / "configuration.md"

SECTIONS = [
    ("LLM (Gemini)", "llm_provider", "search_grounding"),
    ("Pipeline", "n_plans", "exec_n_jobs"),
    ("Data", "max_upload_mb", "profile_sample_rows"),
    ("Storage and server", "workspace_dir", "cors_origins"),
]

HEADER = """# Configuration reference

<!-- Generated by backend/scripts/gen_config_reference.py from backend/src/automl_agent/config.py.
     Do not edit by hand. -->

All settings are read from environment variables or from `backend/.env` (or a repository-root `.env`).
Names are case-insensitive; the environment variable is the upper-case field name.
Copy [`.env.example`](https://github.com/VioniX37/VX04/blob/main/.env.example) to get started.

Settings can also be overridden per command:

* CLI: `automl-agent --set N_PLANS=2 run ...`
* Benchmarks: the `settings` block of a config file, per-variant `settings`, or `--set KEY=VALUE`.
"""


def _type(annotation: object) -> str:
    if isinstance(annotation, type):
        return f"`{annotation.__name__}`"
    text = str(annotation).replace("typing.", "").replace("pathlib.", "")
    if text.startswith("Literal"):
        return " \\| ".join(f"`{a}`" for a in get_args(annotation))
    return "`" + text.replace("|", "\\|") + "`"


def _default(value: object) -> str:
    if value is None:
        return "—"
    if isinstance(value, Path):
        try:
            return f"`<backend>/{value.relative_to(BACKEND_ROOT).as_posix()}`"
        except ValueError:
            return f"`{value.as_posix()}`"
    return f"`{value}`"


def render() -> str:
    """Return the Markdown reference."""
    fields = Settings.model_fields
    names = list(fields)
    parts = [HEADER]
    for title, first, last in SECTIONS:
        block = names[names.index(first) : names.index(last) + 1]
        parts.append(f"\n## {title}\n\n| Variable | Type | Default | Description |\n|---|---|---|---|")
        for name in block:
            f = fields[name]
            env = name.upper()
            if name == "gemini_api_key":
                env = "GEMINI_API_KEY (or GOOGLE_API_KEY)"
            row = f"| `{env}` | {_type(f.annotation)} | {_default(f.default)} | {f.description or ''} |"
            parts.append(row)
    covered = {n for _, a, b in SECTIONS for n in names[names.index(a) : names.index(b) + 1]}
    missing = [n for n in names if n not in covered]
    if missing:
        raise SystemExit(f"settings not assigned to a section: {missing}")
    return "\n".join(parts) + "\n"


def main() -> int:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is out of date; run python scripts/gen_config_reference.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
