"""Tabular classification / regression training script (generated by AutoML-Agent).

Contract: reads CONFIG, trains, evaluates on a hold-out split, and writes
`metrics.json` (primary metric under "score") and `model.joblib` to the cwd.
"""

import json
import time

import joblib
import numpy as np
import pandas as pd
from sklearn import ensemble, linear_model, neighbors, svm
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
    r2_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

CONFIG = __CONFIG__

IS_CLF = CONFIG["task_type"] == "tabular_classification"
SEED = CONFIG.get("random_state", 42)


def load_data():
    df = pd.read_csv(CONFIG["data_path"])
    df = df.dropna(subset=[CONFIG["target"]])
    y = df[CONFIG["target"]]
    X = df.drop(columns=[CONFIG["target"], *[c for c in CONFIG.get("drop_columns", []) if c in df.columns]])
    if CONFIG.get("feature_columns"):
        X = X[[c for c in CONFIG["feature_columns"] if c in X.columns]]
    return X, y


def build_preprocessor(X):
    numeric = X.select_dtypes(include="number").columns.tolist()
    categorical = [c for c in X.columns if c not in numeric]
    return ColumnTransformer([
        ("num", Pipeline([("impute", SimpleImputer(strategy="median")), ("scale", StandardScaler())]), numeric),
        ("cat", Pipeline([
            ("impute", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", max_categories=50)),
        ]), categorical),
    ])


def build_model(family, params):
    if IS_CLF:
        models = {
            "hist_gradient_boosting": lambda: ensemble.HistGradientBoostingClassifier(random_state=SEED),
            "random_forest": lambda: ensemble.RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=SEED),
            "extra_trees": lambda: ensemble.ExtraTreesClassifier(n_estimators=300, n_jobs=-1, random_state=SEED),
            "gradient_boosting": lambda: ensemble.GradientBoostingClassifier(random_state=SEED),
            "logistic_regression": lambda: linear_model.LogisticRegression(max_iter=2000),
            "svm": lambda: svm.SVC(probability=True, random_state=SEED),
            "knn": lambda: neighbors.KNeighborsClassifier(),
        }
    else:
        models = {
            "hist_gradient_boosting": lambda: ensemble.HistGradientBoostingRegressor(random_state=SEED),
            "random_forest": lambda: ensemble.RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=SEED),
            "extra_trees": lambda: ensemble.ExtraTreesRegressor(n_estimators=300, n_jobs=-1, random_state=SEED),
            "gradient_boosting": lambda: ensemble.GradientBoostingRegressor(random_state=SEED),
            "ridge": lambda: linear_model.Ridge(),
            "lasso": lambda: linear_model.Lasso(),
            "svm": lambda: svm.SVR(),
            "knn": lambda: neighbors.KNeighborsRegressor(),
        }
    model = models[family]()
    valid = model.get_params()
    model.set_params(**{k: v for k, v in params.items() if k in valid})
    return model


def evaluate(pipe, X_test, y_test):
    pred = pipe.predict(X_test)
    if IS_CLF:
        m = {
            "accuracy": accuracy_score(y_test, pred),
            "balanced_accuracy": balanced_accuracy_score(y_test, pred),
            "f1_macro": f1_score(y_test, pred, average="macro"),
            "f1_weighted": f1_score(y_test, pred, average="weighted"),
        }
        if hasattr(pipe, "predict_proba"):
            try:
                proba = pipe.predict_proba(X_test)
                m["roc_auc"] = (
                    roc_auc_score(y_test, proba[:, 1]) if proba.shape[1] == 2
                    else roc_auc_score(y_test, proba, multi_class="ovr")
                )
            except ValueError:
                pass
    else:
        m = {
            "rmse": float(np.sqrt(mean_squared_error(y_test, pred))),
            "mae": mean_absolute_error(y_test, pred),
            "r2": r2_score(y_test, pred),
            "mape": mean_absolute_percentage_error(y_test, pred),
        }
    return {k: float(v) for k, v in m.items()}


def main():
    X, y = load_data()
    stratify = y if IS_CLF and y.value_counts().min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=CONFIG.get("test_size", 0.2), random_state=SEED, stratify=stratify
    )
    pipe = Pipeline([
        ("prep", build_preprocessor(X_train)),
        ("model", build_model(CONFIG["model_family"], CONFIG.get("hyperparameters", {}))),
    ])
    start = time.time()
    pipe.fit(X_train, y_train)
    train_time = time.time() - start

    metrics = evaluate(pipe, X_test, y_test)
    result = {
        "metric": CONFIG["metric"],
        "score": metrics.get(CONFIG["metric"]),
        "metrics": metrics,
        "model_family": CONFIG["model_family"],
        "train_time_s": round(train_time, 3),
        "n_train": len(X_train),
        "n_test": len(X_test),
    }
    joblib.dump(pipe, "model.joblib")
    with open("metrics.json", "w") as f:
        json.dump(result, f, indent=2)
    print(json.dumps(result))


if __name__ == "__main__":
    main()
