"""Tabular classification / regression training script (generated by AutoML-Agent).

Contract:
  * reads CONFIG (data + split Parquet files, target, model family, fidelity, ...)
  * trains on the train split (optionally subsampled to `fidelity_rows`),
    early-stops boosting models on the validation split,
  * evaluates on `eval_split` ("valid" during grounding, "test" for the final run),
  * writes metrics.json (primary metric under "score") and, if `save_model`, model.joblib,
  * prints `PROGRESS {json}` lines that the platform streams to the UI.
"""

import json
import time

import joblib
import numpy as np
import pandas as pd
import polars as pl
from sklearn import ensemble, linear_model, neighbors, svm
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
    r2_score,
    roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

CONFIG = __CONFIG__

IS_CLF = CONFIG["task_type"] == "tabular_classification"
SEED = CONFIG.get("random_state", 42)
N_JOBS = CONFIG.get("n_jobs", -1)
SPLIT_IDS = {"train": 0, "valid": 1, "test": 2}
NATIVE_CATEGORICAL = {"lightgbm", "xgboost", "hist_gradient_boosting"}


def progress(stage, **info):
    print("PROGRESS " + json.dumps({"stage": stage, **info}), flush=True)


def feature_columns(schema_names):
    excluded = {CONFIG["target"], *CONFIG.get("drop_columns", [])}
    if CONFIG.get("feature_columns"):
        return [c for c in CONFIG["feature_columns"] if c in schema_names and c not in excluded]
    return [c for c in schema_names if c not in excluded]


def load_split(name, max_rows=None):
    """Return (X, y) for one split as pandas, subsampled via the nested `__r` draw."""
    data = pl.scan_parquet(CONFIG["data_path"])
    lf = pl.concat([data, pl.scan_parquet(CONFIG["split_path"])], how="horizontal")
    lf = lf.filter(pl.col("__split") == SPLIT_IDS[name])
    if max_rows:
        n = lf.select(pl.len()).collect().item()
        if n > max_rows:
            lf = lf.filter(pl.col("__r") < max_rows / n)
    cols = feature_columns(data.collect_schema().names())
    df = lf.select([*cols, CONFIG["target"]]).collect()
    df = df.with_columns(
        [pl.col(c).cast(pl.Categorical) for c, t in df.schema.items() if t == pl.String and c in cols]
        + [pl.col(c).cast(pl.Float32) for c, t in df.schema.items() if t == pl.Float64 and c in cols]
        + [pl.col(c).cast(pl.Int8) for c, t in df.schema.items() if t == pl.Boolean and c in cols]
    )
    pdf = df.to_pandas()
    return pdf[cols], pdf[CONFIG["target"]]


def align_categories(train, others):
    """Give every categorical column the train split's categories (unseen values -> NaN)."""
    for col in train.select_dtypes("category").columns:
        cats = train[col].cat.categories
        for frame in others:
            frame[col] = pd.Categorical(frame[col].astype(object), categories=cats)


def encode_labels(y_train, *ys):
    classes = np.array(sorted(pd.unique(y_train.dropna()), key=str), dtype=object)
    lookup = {c: i for i, c in enumerate(classes)}
    encoded = [y.map(lookup) for y in (y_train, *ys)]
    return classes, encoded


def sklearn_preprocessor(X):
    numeric = X.select_dtypes(include="number").columns.tolist()
    categorical = [c for c in X.columns if c not in numeric]
    return ColumnTransformer([
        ("num", Pipeline([("impute", SimpleImputer(strategy="median")), ("scale", StandardScaler())]), numeric),
        ("cat", Pipeline([
            ("impute", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", max_categories=30)),
        ]), categorical),
    ])


def with_params(model, params):
    valid = model.get_params()
    return model.set_params(**{k: v for k, v in params.items() if k in valid})


def build_model(family, params):
    if family == "lightgbm":
        import lightgbm as lgb
        cls = lgb.LGBMClassifier if IS_CLF else lgb.LGBMRegressor
        base = cls(n_estimators=2000, learning_rate=0.05, num_leaves=63, subsample=0.8, subsample_freq=1,
                   colsample_bytree=0.8, random_state=SEED, n_jobs=N_JOBS, verbose=-1)
        return with_params(base, params)
    if family == "xgboost":
        import xgboost as xgb
        cls = xgb.XGBClassifier if IS_CLF else xgb.XGBRegressor
        base = cls(tree_method="hist", enable_categorical=True, n_estimators=2000, learning_rate=0.05,
                   max_depth=8, subsample=0.8, colsample_bytree=0.8, early_stopping_rounds=50,
                   random_state=SEED, n_jobs=N_JOBS)
        return with_params(base, params)
    if family == "hist_gradient_boosting":
        cls = ensemble.HistGradientBoostingClassifier if IS_CLF else ensemble.HistGradientBoostingRegressor
        return with_params(cls(categorical_features="from_dtype", early_stopping=True, random_state=SEED), params)
    if IS_CLF:
        models = {
            "random_forest": lambda: ensemble.RandomForestClassifier(n_estimators=300, n_jobs=N_JOBS, random_state=SEED),
            "extra_trees": lambda: ensemble.ExtraTreesClassifier(n_estimators=300, n_jobs=N_JOBS, random_state=SEED),
            "gradient_boosting": lambda: ensemble.GradientBoostingClassifier(random_state=SEED),
            "logistic_regression": lambda: linear_model.LogisticRegression(max_iter=2000),
            "sgd": lambda: linear_model.SGDClassifier(loss="log_loss", early_stopping=True, random_state=SEED),
            "svm": lambda: svm.SVC(probability=True, random_state=SEED),
            "knn": lambda: neighbors.KNeighborsClassifier(n_jobs=N_JOBS),
        }
    else:
        models = {
            "random_forest": lambda: ensemble.RandomForestRegressor(n_estimators=300, n_jobs=N_JOBS, random_state=SEED),
            "extra_trees": lambda: ensemble.ExtraTreesRegressor(n_estimators=300, n_jobs=N_JOBS, random_state=SEED),
            "gradient_boosting": lambda: ensemble.GradientBoostingRegressor(random_state=SEED),
            "ridge": lambda: linear_model.Ridge(),
            "lasso": lambda: linear_model.Lasso(),
            "sgd": lambda: linear_model.SGDRegressor(early_stopping=True, random_state=SEED),
            "svm": lambda: svm.SVR(),
            "knn": lambda: neighbors.KNeighborsRegressor(n_jobs=N_JOBS),
        }
    return with_params(models[family](), params)


def prepare_native(family, X_train, others):
    """HistGradientBoosting accepts at most 255 categories: fall back to ordinal codes above that."""
    if family != "hist_gradient_boosting":
        return
    for col in X_train.select_dtypes("category").columns:
        if len(X_train[col].cat.categories) > 250:
            for frame in (X_train, *others):
                frame[col] = frame[col].cat.codes.replace(-1, np.nan).astype("float32")


def fit(family, model, X_train, y_train, X_valid, y_valid):
    if family == "lightgbm":
        import lightgbm as lgb
        model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)],
                  callbacks=[lgb.early_stopping(50, verbose=False)])
    elif family == "xgboost":
        model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)], verbose=False)
    else:
        model.fit(X_train, y_train)
    return model


def evaluate(model, X, y):
    pred = model.predict(X)
    if IS_CLF:
        pred = np.asarray(pred).astype(int)
        m = {
            "accuracy": accuracy_score(y, pred),
            "balanced_accuracy": balanced_accuracy_score(y, pred),
            "f1_macro": f1_score(y, pred, average="macro"),
            "f1_weighted": f1_score(y, pred, average="weighted"),
        }
        if hasattr(model, "predict_proba"):
            try:
                proba = model.predict_proba(X)
                m["roc_auc"] = (
                    roc_auc_score(y, proba[:, 1]) if proba.shape[1] == 2
                    else roc_auc_score(y, proba, multi_class="ovr")
                )
            except ValueError:
                pass
    else:
        m = {
            "rmse": float(np.sqrt(mean_squared_error(y, pred))),
            "mae": mean_absolute_error(y, pred),
            "r2": r2_score(y, pred),
            "mape": mean_absolute_percentage_error(y, pred),
        }
        if (y >= 0).all():
            m["rmsle"] = float(np.sqrt(np.mean((np.log1p(np.clip(pred, 0, None)) - np.log1p(y)) ** 2)))
    return {k: float(v) for k, v in m.items()}


def main():
    family = CONFIG["model_family"]
    eval_split = CONFIG.get("eval_split", "test")
    progress("loading", fidelity_rows=CONFIG.get("fidelity_rows"))
    X_train, y_train = load_split("train", CONFIG.get("fidelity_rows"))
    X_valid, y_valid = load_split("valid", CONFIG.get("eval_max_rows"))
    X_eval, y_eval = (X_valid, y_valid) if eval_split == "valid" else load_split("test")
    others = [X_valid] if eval_split == "valid" else [X_valid, X_eval]
    align_categories(X_train, others)
    categories = {c: X_train[c].cat.categories.tolist() for c in X_train.select_dtypes("category").columns}

    classes = None
    if IS_CLF:
        classes, (y_train, y_valid, y_eval) = encode_labels(y_train, y_valid, y_eval)
        keep_v, keep_e = y_valid.notna(), y_eval.notna()  # drop labels unseen in train
        X_valid, y_valid = X_valid[keep_v], y_valid[keep_v].astype(int)
        X_eval, y_eval = X_eval[keep_e], y_eval[keep_e].astype(int)
        y_train = y_train.astype(int)
        if eval_split == "valid":
            X_eval, y_eval = X_valid, y_valid

    if family in NATIVE_CATEGORICAL:
        prepare_native(family, X_train, [X_valid] if X_eval is X_valid else [X_valid, X_eval])
        model = build_model(family, CONFIG.get("hyperparameters", {}))
    else:
        model = Pipeline([
            ("prep", sklearn_preprocessor(X_train)),
            ("model", build_model(family, CONFIG.get("hyperparameters", {}))),
        ])

    progress("training", family=family, n_train=len(X_train))
    start = time.time()
    fit(family, model, X_train, y_train, X_valid, y_valid)
    train_time = time.time() - start

    progress("evaluating", split=eval_split, n_eval=len(X_eval))
    metrics = evaluate(model, X_eval, y_eval)
    result = {
        "metric": CONFIG["metric"],
        "score": metrics.get(CONFIG["metric"]),
        "metrics": metrics,
        "split": eval_split,
        "model_family": family,
        "train_time_s": round(train_time, 3),
        "n_train": len(X_train),
        "n_eval": len(X_eval),
        "fidelity_rows": CONFIG.get("fidelity_rows"),
        "best_iteration": getattr(model, "best_iteration_", None) or getattr(model, "best_iteration", None),
    }
    if eval_split == "test":
        result["metrics_valid"] = evaluate(model, X_valid, y_valid)
    if CONFIG.get("save_model", True):
        joblib.dump(
            {
                "model": model,
                "classes": classes,
                "features": list(X_train.columns),
                # Inference metadata — kept in sync with execution/inference.py
                "task_type": CONFIG["task_type"],
                "target": CONFIG["target"],
                "drop_columns": CONFIG.get("drop_columns", []),
                # Training-time dtypes and category levels, replayed by inference.prepare_features
                "dtypes": {c: str(t) for c, t in X_train.dtypes.items()},
                "categories": categories,
                "ordinal_columns": [c for c in categories if str(X_train[c].dtype) != "category"],
                # Columns present in the training data but not used as features: accepted and ignored
                "ignored_columns": [
                    c for c in pl.scan_parquet(CONFIG["data_path"]).collect_schema().names()
                    if c not in X_train.columns and c != CONFIG["target"]
                ],
                "config": CONFIG,
            },
            "model.joblib",
        )
    with open("metrics.json", "w") as f:
        json.dump(result, f, indent=2, default=str)
    progress("done", score=result["score"])
    print(json.dumps(result, default=str))


if __name__ == "__main__":
    main()
