"""Text classification training script (generated by AutoML-Agent).

Contract: see tabular.py. Two strategies:
  * TF-IDF families (logistic_regression, linear_svm, naive_bayes, sgd) load the
    (possibly subsampled) train split into memory;
  * `sgd_hashing` streams the data in chunks with a stateless HashingVectorizer and
    `partial_fit`, so corpora larger than RAM can be trained on.
"""

import json
import time

import joblib
import numpy as np
import polars as pl
from sklearn import linear_model, naive_bayes, svm
from sklearn.feature_extraction.text import HashingVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, roc_auc_score
from sklearn.pipeline import Pipeline

CONFIG = __CONFIG__

SEED = CONFIG.get("random_state", 42)
SPLIT_IDS = {"train": 0, "valid": 1, "test": 2}
CHUNK_ROWS = CONFIG.get("chunk_rows", 200_000)


def progress(stage, **info):
    print("PROGRESS " + json.dumps({"stage": stage, **info}), flush=True)


def split_frame():
    data = pl.scan_parquet(CONFIG["data_path"]).select([CONFIG["text_column"], CONFIG["target"]])
    return pl.concat([data, pl.scan_parquet(CONFIG["split_path"])], how="horizontal")


def split_filter(lf, name, max_rows=None):
    lf = lf.filter(pl.col("__split") == SPLIT_IDS[name])
    if max_rows:
        n = lf.select(pl.len()).collect().item()
        if n > max_rows:
            lf = lf.filter(pl.col("__r") < max_rows / n)
    return lf


def load(name, max_rows=None):
    df = split_filter(split_frame(), name, max_rows).select([CONFIG["text_column"], CONFIG["target"]]).collect()
    return df[CONFIG["text_column"]].fill_null("").to_list(), df[CONFIG["target"]].cast(pl.String).to_list()


def iter_chunks(name, max_rows=None):
    """Yield (texts, labels) chunks of one split without loading it all into memory."""
    base = pl.scan_parquet(CONFIG["data_path"]).select([CONFIG["text_column"], CONFIG["target"]])
    split = pl.scan_parquet(CONFIG["split_path"])
    total = base.select(pl.len()).collect().item()
    frac = None
    if max_rows:
        n = split.filter(pl.col("__split") == SPLIT_IDS[name]).select(pl.len()).collect().item()
        frac = max_rows / n if n > max_rows else None
    for offset in range(0, total, CHUNK_ROWS):
        chunk = pl.concat([base.slice(offset, CHUNK_ROWS), split.slice(offset, CHUNK_ROWS)], how="horizontal")
        chunk = chunk.filter(pl.col("__split") == SPLIT_IDS[name])
        if frac is not None:
            chunk = chunk.filter(pl.col("__r") < frac)
        df = chunk.collect()
        if len(df):
            yield df[CONFIG["text_column"]].fill_null("").to_list(), df[CONFIG["target"]].cast(pl.String).to_list()


def with_params(model, params):
    valid = model.get_params()
    return model.set_params(**{k: v for k, v in params.items() if k in valid})


def build_tfidf_model(family, params):
    models = {
        "logistic_regression": lambda: linear_model.LogisticRegression(max_iter=2000),
        "linear_svm": lambda: svm.LinearSVC(random_state=SEED),
        "sgd": lambda: linear_model.SGDClassifier(loss="modified_huber", random_state=SEED),
        "naive_bayes": lambda: naive_bayes.ComplementNB(),
    }
    return Pipeline([
        ("tfidf", TfidfVectorizer(lowercase=True, ngram_range=(1, 2), min_df=2, sublinear_tf=True,
                                  max_features=CONFIG.get("max_features", 500_000))),
        ("model", with_params(models[family](), params)),
    ])


def metrics_for(y_true, pred, proba=None):
    m = {
        "accuracy": accuracy_score(y_true, pred),
        "balanced_accuracy": balanced_accuracy_score(y_true, pred),
        "f1_macro": f1_score(y_true, pred, average="macro"),
        "f1_weighted": f1_score(y_true, pred, average="weighted"),
    }
    if proba is not None and proba.shape[1] == 2:
        try:
            m["roc_auc"] = roc_auc_score(y_true, proba[:, 1])
        except ValueError:
            pass
    return {k: float(v) for k, v in m.items()}


def evaluate_in_memory(model, name, max_rows=None):
    X, y = load(name, max_rows)
    pred = model.predict(X)
    # classes_ is sorted, as is sklearn's implicit label order in roc_auc_score.
    proba = model.predict_proba(X) if hasattr(model, "predict_proba") else None
    return metrics_for(y, pred, proba), len(y)


def evaluate_streaming(model, vectorizer, name, max_rows=None):
    preds, labels, probas = [], [], []
    for texts, y in iter_chunks(name, max_rows):
        Xc = vectorizer.transform(texts)
        preds.extend(model.predict(Xc))
        labels.extend(y)
        if hasattr(model, "predict_proba") and len(model.classes_) == 2:
            probas.append(model.predict_proba(Xc))
    proba = np.vstack(probas) if probas else None
    return metrics_for(labels, preds, proba), len(labels)


def main():
    family = CONFIG["model_family"]
    eval_split = CONFIG.get("eval_split", "test")
    fidelity = CONFIG.get("fidelity_rows")
    params = CONFIG.get("hyperparameters", {})
    start = time.time()
    progress("loading", fidelity_rows=fidelity)

    if family == "sgd_hashing":
        vectorizer = HashingVectorizer(n_features=2**20, alternate_sign=False, ngram_range=(1, 2), norm="l2")
        model = with_params(linear_model.SGDClassifier(loss="modified_huber", alpha=1e-6, random_state=SEED), params)
        classes = np.array(sorted(
            split_filter(split_frame(), "train").select(pl.col(CONFIG["target"]).cast(pl.String).unique())
            .collect().to_series().drop_nulls().to_list()
        ))
        n_train = 0
        for epoch in range(CONFIG.get("epochs", 2)):
            for texts, y in iter_chunks("train", fidelity):
                model.partial_fit(vectorizer.transform(texts), y, classes=classes)
                n_train += len(y) if epoch == 0 else 0
            progress("training", epoch=epoch + 1, n_train=n_train)
        train_time = time.time() - start
        evaluate = lambda name, cap=None: evaluate_streaming(model, vectorizer, name, cap)  # noqa: E731
        artifact = {"model": model, "vectorizer": vectorizer}
    else:
        X_train, y_train = load("train", fidelity)
        n_train = len(y_train)
        progress("training", family=family, n_train=n_train)
        model = build_tfidf_model(family, params)
        model.fit(X_train, y_train)
        del X_train
        train_time = time.time() - start
        evaluate = lambda name, cap=None: evaluate_in_memory(model, name, cap)  # noqa: E731
        artifact = {"model": model}

    progress("evaluating", split=eval_split)
    cap = CONFIG.get("eval_max_rows") if eval_split == "valid" else None
    metrics, n_eval = evaluate(eval_split, cap)
    result = {
        "metric": CONFIG["metric"],
        "score": metrics.get(CONFIG["metric"]),
        "metrics": metrics,
        "split": eval_split,
        "model_family": family,
        "train_time_s": round(train_time, 3),
        "n_train": n_train,
        "n_eval": n_eval,
        "fidelity_rows": fidelity,
    }
    if eval_split == "test":
        result["metrics_valid"] = evaluate("valid", CONFIG.get("eval_max_rows"))[0]
    if CONFIG.get("save_model", True):
        joblib.dump(artifact, "model.joblib")
    with open("metrics.json", "w") as f:
        json.dump(result, f, indent=2)
    progress("done", score=result["score"])
    print(json.dumps(result))


if __name__ == "__main__":
    main()
