"""Text classification training script (generated by AutoML-Agent).

Contract: reads CONFIG, trains, evaluates on a hold-out split, and writes
`metrics.json` (primary metric under "score") and `model.joblib` to the cwd.
"""

import json
import time

import joblib
import pandas as pd
from sklearn import linear_model, naive_bayes, svm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

CONFIG = __CONFIG__

SEED = CONFIG.get("random_state", 42)


def load_data():
    df = pd.read_csv(CONFIG["data_path"])
    df = df.dropna(subset=[CONFIG["target"], CONFIG["text_column"]])
    return df[CONFIG["text_column"]].astype(str), df[CONFIG["target"]]


def build_model(family, params):
    models = {
        "logistic_regression": lambda: linear_model.LogisticRegression(max_iter=2000),
        "linear_svm": lambda: svm.LinearSVC(random_state=SEED),
        "sgd": lambda: linear_model.SGDClassifier(loss="modified_huber", random_state=SEED),
        "naive_bayes": lambda: naive_bayes.ComplementNB(),
    }
    model = models[family]()
    valid = model.get_params()
    model.set_params(**{k: v for k, v in params.items() if k in valid})
    return model


def main():
    X, y = load_data()
    stratify = y if y.value_counts().min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=CONFIG.get("test_size", 0.2), random_state=SEED, stratify=stratify
    )
    pipe = Pipeline([
        ("tfidf", TfidfVectorizer(lowercase=True, ngram_range=(1, 2), min_df=2, sublinear_tf=True)),
        ("model", build_model(CONFIG["model_family"], CONFIG.get("hyperparameters", {}))),
    ])
    start = time.time()
    pipe.fit(X_train, y_train)
    train_time = time.time() - start

    pred = pipe.predict(X_test)
    metrics = {
        "accuracy": accuracy_score(y_test, pred),
        "balanced_accuracy": balanced_accuracy_score(y_test, pred),
        "f1_macro": f1_score(y_test, pred, average="macro"),
        "f1_weighted": f1_score(y_test, pred, average="weighted"),
    }
    if hasattr(pipe, "predict_proba") and y.nunique() == 2:
        metrics["roc_auc"] = roc_auc_score(y_test, pipe.predict_proba(X_test)[:, 1])
    metrics = {k: float(v) for k, v in metrics.items()}

    result = {
        "metric": CONFIG["metric"],
        "score": metrics.get(CONFIG["metric"]),
        "metrics": metrics,
        "model_family": CONFIG["model_family"],
        "train_time_s": round(train_time, 3),
        "n_train": len(X_train),
        "n_test": len(X_test),
    }
    joblib.dump(pipe, "model.joblib")
    with open("metrics.json", "w") as f:
        json.dump(result, f, indent=2)
    print(json.dumps(result))


if __name__ == "__main__":
    main()
