"""Time-series forecasting training script (generated by AutoML-Agent).

Contract:
  * reads CONFIG (data + split Parquet files, target, time_column, series_id_columns, horizon, frequency, ...)
  * the split is temporal: train, valid and test are contiguous time blocks,
  * trains on the train block (subsampled to the most recent `fidelity_rows` via the suffix-window `__r`),
  * evaluates on `eval_split` ("valid" during grounding, "test" for the final run) with a rolling-origin
    backtest: every `horizon` steps a new forecast is made from all actual values before it,
  * always scores the seasonal-naive and ETS baselines the same way, as the floor,
  * writes metrics.json (primary metric under "score", baselines, `beats_seasonal_naive`) and, if
    `save_model`, model.joblib and the test-block predictions,
  * prints `PROGRESS {json}` lines that the platform streams to the UI.

The models, features and backtest live in `automl_agent.execution.forecasting`, which the serving
layer uses too, so a served forecast is computed exactly like an evaluated one.
"""

import json
import time

import joblib
import numpy as np
import pandas as pd
import polars as pl

from automl_agent.execution import forecasting as fc

CONFIG = __CONFIG__

SEED = CONFIG.get("random_state", 42)
N_JOBS = CONFIG.get("n_jobs", -1)
SPLIT_IDS = {"train": 0, "valid": 1, "test": 2}
HORIZON = int(CONFIG.get("horizon") or 14)
FREQ = CONFIG.get("frequency") or "D"


def progress(stage, **info):
    print("PROGRESS " + json.dumps({"stage": stage, **info}), flush=True)


def load():
    """The dataset with its split columns, plus the resolved time and series-id columns."""
    data = pl.scan_parquet(CONFIG["data_path"])
    schema = data.collect_schema()
    names = schema.names()
    time_col = CONFIG.get("time_column")
    if not time_col or time_col not in names:
        time_col = next(
            (c for c in names if schema[c].is_temporal() or c.lower() in ("date", "datetime", "timestamp", "ds")),
            names[0],
        )
    series_cols = [c for c in (CONFIG.get("series_id_columns") or []) if c in names and c not in (time_col, CONFIG["target"])]
    frame = pl.concat([data, pl.scan_parquet(CONFIG["split_path"])], how="horizontal").collect().to_pandas()
    return frame, time_col, series_cols


def block(frame, name, time_col, series_cols, max_rows=None):
    part = frame[frame["__split"] == SPLIT_IDS[name]]
    if max_rows and len(part) > max_rows:
        part = part[part["__r"] < max_rows / len(part)]  # the most recent rows
    return fc.to_series(part, time_col, CONFIG["target"], series_cols)


def evaluate(model, history, eval_block):
    preds = fc.backtest(model, history, eval_block)
    y_true = np.concatenate([v for _, v in eval_block.values()]) if eval_block else np.array([])
    y_pred = np.concatenate([preds[sid] for sid in eval_block]) if eval_block else np.array([])
    return fc.metrics(y_true, y_pred), preds


def merge(*blocks):
    """Concatenate per-series blocks in time order."""
    out = {}
    for b in blocks:
        for sid, (dates, values) in b.items():
            if sid in out:
                out[sid] = (out[sid][0].append(dates), np.concatenate([out[sid][1], values]))
            else:
                out[sid] = (dates, values)
    return out


def main():
    family = CONFIG.get("model_family", "lightgbm")
    eval_split = CONFIG.get("eval_split", "test")
    metric = CONFIG.get("metric", "smape")
    progress("loading", fidelity_rows=CONFIG.get("fidelity_rows"))
    frame, time_col, series_cols = load()
    train = block(frame, "train", time_col, series_cols, CONFIG.get("fidelity_rows"))
    valid = block(frame, "valid", time_col, series_cols)
    test = block(frame, "test", time_col, series_cols)
    eval_block = valid if eval_split == "valid" else test
    history = train if eval_split == "valid" else merge(train, valid)
    n_train = int(sum(len(v) for _, v in train.values()))

    progress("training", family=family, n_train=n_train, horizon=HORIZON)
    start = time.time()
    model = fc.fit(
        family, train, horizon=HORIZON, freq=FREQ, valid=valid if eval_split == "test" else None,
        params=CONFIG.get("hyperparameters", {}), seed=SEED, n_jobs=N_JOBS,
    )  # fmt: skip
    train_time = time.time() - start

    progress("evaluating", split=eval_split, n_eval=int(sum(len(v) for _, v in eval_block.values())))
    metrics, preds = evaluate(model, history, eval_block)
    baselines = {}
    for name in ("seasonal_naive", "ets"):
        baseline = fc.fit(name, train, horizon=HORIZON, freq=FREQ)
        baselines[name] = evaluate(baseline, history, eval_block)[0]
    score = metrics.get(metric, metrics["smape"])
    naive_score = baselines["seasonal_naive"].get(metric, baselines["seasonal_naive"]["smape"])

    result = {
        "metric": metric,
        "score": score,
        "metrics": metrics,
        "split": eval_split,
        "model_family": family,
        "train_time_s": round(train_time, 3),
        "n_train": n_train,
        "n_eval": int(sum(len(v) for _, v in eval_block.values())),
        "fidelity_rows": CONFIG.get("fidelity_rows"),
        "horizon": HORIZON,
        "frequency": FREQ,
        "evaluation": "rolling-origin backtest, one forecast of up to `horizon` steps per window",
        "baseline_scores": {name: m.get(metric, m["smape"]) for name, m in baselines.items()},
        "seasonal_naive_score": naive_score,
        "beats_seasonal_naive": family == "seasonal_naive" or bool(score < naive_score),
    }
    with open("metrics.json", "w") as f:
        json.dump(result, f, indent=2)

    if CONFIG.get("save_model", True):
        state = fc.serving_state(model, merge(train, valid, test))
        known = {c: sorted(frame[c].dropna().astype(str).unique().tolist()) for c in series_cols}
        features = [*series_cols, "horizon_step"]
        joblib.dump(
            {
                "model": state,
                "task_type": CONFIG["task_type"],
                "target": CONFIG["target"],
                "features": features,
                "time_column": time_col,
                "series_id_columns": series_cols,
                "horizon": HORIZON,
                "frequency": FREQ,
                "drop_columns": CONFIG.get("drop_columns", []),
                "ignored_columns": [c for c in frame.columns if c not in features and not c.startswith("__")],
                "dtypes": {**dict.fromkeys(series_cols, "category"), "horizon_step": "int64"},
                "categories": known,
                "config": CONFIG,
            },
            "model.joblib",
        )
        if eval_split == "test":
            rows = [
                {"series": sid, "date": d.isoformat(), "y_true": float(y), "y_pred": float(p)}
                for sid, (dates, values) in eval_block.items()
                for d, y, p in zip(dates, values, preds[sid])
            ]
            pd.DataFrame(rows).to_parquet("test_predictions.parquet", index=False)

    progress("done", score=score, beats_seasonal_naive=result["beats_seasonal_naive"])
    print(json.dumps(result))


if __name__ == "__main__":
    main()
