"""Time-series forecasting training script (generated by AutoML-Agent).

Contract:
  * reads CONFIG (data + split Parquet files, target, time_column, horizon, frequency, ...)
  * trains on the train split (optionally subsampled via suffix-window `__r` to `fidelity_rows`),
  * runs seasonal-naive and ETS baselines as the floor,
  * trains LightGBM on lag, rolling-window and calendar features using direct multi-horizon forecasting,
  * evaluates on `eval_split` ("valid" during grounding, "test" for the final run),
  * writes metrics.json (including baseline comparisons and `beats_seasonal_naive`),
  * saves model.joblib if `save_model`,
  * prints PROGRESS lines for the UI.
"""

import json
import time
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
import polars as pl
from sklearn.preprocessing import OrdinalEncoder

try:
    import lightgbm as lgb
except ImportError:
    lgb = None

try:
    CONFIG = __CONFIG__
except NameError:
    CONFIG = {}

SEED = CONFIG.get("random_state", 42)
N_JOBS = CONFIG.get("n_jobs", -1)
SPLIT_IDS = {"train": 0, "valid": 1, "test": 2}
HORIZON = int(CONFIG.get("horizon") or 14)
FREQ = CONFIG.get("frequency") or "D"


def progress(stage, **info):
    print("PROGRESS " + json.dumps({"stage": stage, **info}), flush=True)


def get_seasonality(freq: str) -> int:
    f = freq.upper()
    if "H" in f:
        return 24
    if "W" in f:
        return 52
    if "M" in f:
        return 12
    if "MIN" in f:
        return 60
    return 7  # Default daily -> weekly cycle


def compute_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    yt = np.asarray(y_true, dtype=float)
    yp = np.asarray(y_pred, dtype=float)
    # sMAPE: 200 * mean(|y - p| / (|y| + |p|))
    denom = np.abs(yt) + np.abs(yp)
    mask = denom > 1e-8
    smape_val = float(np.mean(np.where(mask, 200.0 * np.abs(yt - yp) / denom, 0.0))) if len(yt) else 0.0
    mae_val = float(np.mean(np.abs(yt - yp))) if len(yt) else 0.0
    rmse_val = float(np.sqrt(np.mean((yt - yp) ** 2))) if len(yt) else 0.0
    mape_val = float(np.mean(np.abs((yt - yp) / np.maximum(np.abs(yt), 1e-8)))) * 100.0 if len(yt) else 0.0
    return {
        "smape": smape_val,
        "mae": mae_val,
        "rmse": rmse_val,
        "mape": mape_val,
    }


def load_dataset():
    """Load and sort the dataset by time and series."""
    data = pl.scan_parquet(CONFIG["data_path"])
    split = pl.scan_parquet(CONFIG["split_path"])
    lf = pl.concat([data, split], how="horizontal")

    schema = data.collect_schema()
    names = schema.names()

    # Determine time column
    time_col = CONFIG.get("time_column")
    if not time_col or time_col not in names:
        for c in names:
            if schema[c].is_temporal() or c.lower() in ("date", "datetime", "timestamp", "time", "ds"):
                time_col = c
                break
    if not time_col:
        time_col = names[0]

    # Determine series ID columns
    series_cols = [c for c in (CONFIG.get("series_id_columns") or []) if c in names and c != time_col and c != CONFIG["target"]]

    df = lf.collect()
    pdf = df.to_pandas()

    # Convert time_col to datetime
    pdf["__dt"] = pd.to_datetime(pdf[time_col], errors="coerce")
    if pdf["__dt"].isna().all():
        pdf["__dt"] = pd.date_range("2020-01-01", periods=len(pdf), freq=FREQ)

    # Composite series ID
    if series_cols:
        pdf["__series"] = pdf[series_cols].astype(str).agg("-".join, axis=1)
    else:
        pdf["__series"] = "series_0"

    pdf = pdf.sort_values(["__series", "__dt"]).reset_index(drop=True)
    return pdf, time_col, series_cols


class SeasonalNaiveModel:
    """Seasonal naive baseline forecaster."""

    def __init__(self, season_length: int):
        self.season_length = season_length
        self.history = {}

    def fit(self, df: pd.DataFrame, target_col: str):
        for sid, group in df.groupby("__series"):
            self.history[sid] = group[target_col].dropna().to_numpy()
        return self

    def predict(self, series_ids_or_df: Any, horizon_steps: list[int] | None = None) -> np.ndarray:
        if isinstance(series_ids_or_df, pd.DataFrame):
            df = series_ids_or_df
            s_col = next((c for c in ("__series", "store_id", "store", "series_id", "id") if c in df.columns), None)
            s_ids = df[s_col].astype(str).tolist() if s_col else ["series_0"] * len(df)
            h_steps = (
                df["horizon_step"].astype(int).tolist()
                if "horizon_step" in df.columns
                else list(range(1, len(df) + 1))
            )
            return self.predict(s_ids, h_steps)
        series_ids = series_ids_or_df
        preds = []
        for sid, h in zip(series_ids, horizon_steps or [1] * len(series_ids), strict=False):
            hist = self.history.get(sid, np.array([0.0]))
            n = len(hist)
            if n == 0:
                preds.append(0.0)
            elif n < self.season_length:
                preds.append(float(hist[-1]))
            else:
                idx = n - (self.season_length - ((h - 1) % self.season_length))
                if 0 <= idx < n:
                    preds.append(float(hist[idx]))
                else:
                    preds.append(float(hist[-1]))
        return np.array(preds, dtype=float)


class ETSModel:
    """Holt-Winters Exponential Smoothing baseline with level, trend, and seasonality."""

    def __init__(self, season_length: int, alpha: float = 0.2, beta: float = 0.05, gamma: float = 0.1):
        self.season_length = season_length
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.states = {}

    def fit(self, df: pd.DataFrame, target_col: str):
        S = max(self.season_length, 2)
        for sid, group in df.groupby("__series"):
            y = group[target_col].dropna().to_numpy()
            n = len(y)
            if n < S:
                level = y[-1] if n > 0 else 0.0
                self.states[sid] = {"level": level, "trend": 0.0, "season": np.zeros(S)}
                continue

            level = np.mean(y[:S])
            trend = (np.mean(y[S:2*S]) - level) / S if n >= 2 * S else 0.0
            season = np.zeros(S)
            for i in range(S):
                season[i] = y[i] - level

            for t in range(n):
                val = y[t]
                prev_level = level
                prev_trend = trend
                s_idx = t % S
                level = self.alpha * (val - season[s_idx]) + (1 - self.alpha) * (prev_level + prev_trend)
                trend = self.beta * (level - prev_level) + (1 - self.beta) * prev_trend
                season[s_idx] = self.gamma * (val - level) + (1 - self.gamma) * season[s_idx]

            self.states[sid] = {"level": level, "trend": trend, "season": season}
        return self

    def predict(self, series_ids_or_df: Any, horizon_steps: list[int] | None = None) -> np.ndarray:
        if isinstance(series_ids_or_df, pd.DataFrame):
            df = series_ids_or_df
            s_col = next((c for c in ("__series", "store_id", "store", "series_id", "id") if c in df.columns), None)
            s_ids = df[s_col].astype(str).tolist() if s_col else ["series_0"] * len(df)
            h_steps = (
                df["horizon_step"].astype(int).tolist()
                if "horizon_step" in df.columns
                else list(range(1, len(df) + 1))
            )
            return self.predict(s_ids, h_steps)
        series_ids = series_ids_or_df
        preds = []
        S = max(self.season_length, 2)
        for sid, h in zip(series_ids, horizon_steps or [1] * len(series_ids), strict=False):
            st = self.states.get(sid)
            if not st:
                preds.append(0.0)
                continue
            pred = st["level"] + h * st["trend"] + st["season"][(h - 1) % S]
            preds.append(float(pred))
        return np.array(preds, dtype=float)


def build_direct_features(
    df: pd.DataFrame,
    target_col: str,
    horizon: int,
    is_training: bool = True,
    origin_df: pd.DataFrame | None = None,
) -> tuple[pd.DataFrame, np.ndarray | None]:
    """Build direct multi-horizon features strictly from past data (leakage guard).

    For origin time t and step h in 1..H:
      * Target: y(t + h)
      * Lag features: y(t), y(t-1), y(t-6), y(t-13)  -- strictly <= t
      * Rolling stats: mean and std over t-6..t and t-13..t  -- strictly <= t
      * Calendar features: evaluated at the target time t + h
    """
    rows = []
    y_vals = []

    # If evaluating, origin_df contains the history strictly before the evaluation window
    source_df = df if origin_df is None else pd.concat([origin_df, df], ignore_index=True)
    source_df = source_df.sort_values(["__series", "__dt"]).reset_index(drop=True)

    for sid, group in source_df.groupby("__series"):
        group = group.reset_index(drop=True)
        times = group["__dt"].to_numpy()
        targets = group[target_col].to_numpy()
        n = len(group)

        if is_training:
            # Origins t where t + horizon <= n
            min_history = 14
            for t_idx in range(min_history, n - horizon):
                # Features from origin t_idx (strictly <= t_idx)
                y_t = targets[t_idx]
                y_t_1 = targets[t_idx - 1]
                y_t_6 = targets[t_idx - 6] if t_idx >= 6 else y_t_1
                y_t_13 = targets[t_idx - 13] if t_idx >= 13 else y_t_6

                w7 = targets[max(0, t_idx - 6) : t_idx + 1]
                w14 = targets[max(0, t_idx - 13) : t_idx + 1]
                mean_7 = float(np.mean(w7))
                std_7 = float(np.std(w7))
                mean_14 = float(np.mean(w14))
                std_14 = float(np.std(w14))

                for h in range(1, horizon + 1):
                    target_time = pd.Timestamp(times[t_idx + h])
                    future_y = targets[t_idx + h]
                    if np.isnan(future_y):
                        continue

                    rows.append({
                        "__series": sid,
                        "horizon_step": h,
                        "lag_1": y_t,
                        "lag_2": y_t_1,
                        "lag_7": y_t_6,
                        "lag_14": y_t_13,
                        "rolling_mean_7": mean_7,
                        "rolling_std_7": std_7,
                        "rolling_mean_14": mean_14,
                        "rolling_std_14": std_14,
                        "dayofweek": target_time.dayofweek,
                        "month": target_time.month,
                        "day": target_time.day,
                        "is_weekend": int(target_time.dayofweek >= 5),
                    })
                    y_vals.append(future_y)
        else:
            # Forecasting eval points directly
            # Origin is the last point in origin_df (or history before the eval split)
            if origin_df is not None:
                orig_group = origin_df[origin_df["__series"] == sid]
                hist_targets = orig_group[target_col].dropna().to_numpy()
            else:
                hist_targets = targets[:-horizon]

            if len(hist_targets) == 0:
                hist_targets = np.array([0.0])

            t_len = len(hist_targets)
            y_t = hist_targets[-1]
            y_t_1 = hist_targets[-2] if t_len >= 2 else y_t
            y_t_6 = hist_targets[-7] if t_len >= 7 else y_t_1
            y_t_13 = hist_targets[-14] if t_len >= 14 else y_t_6

            w7 = hist_targets[-min(7, t_len):]
            w14 = hist_targets[-min(14, t_len):]
            mean_7 = float(np.mean(w7))
            std_7 = float(np.std(w7))
            mean_14 = float(np.mean(w14))
            std_14 = float(np.std(w14))

            eval_group = df[df["__series"] == sid].reset_index(drop=True)
            for step_i, row_val in eval_group.iterrows():
                h_step = (step_i % horizon) + 1
                target_time = pd.Timestamp(row_val["__dt"])
                rows.append({
                    "__series": sid,
                    "horizon_step": h_step,
                    "lag_1": y_t,
                    "lag_2": y_t_1,
                    "lag_7": y_t_6,
                    "lag_14": y_t_13,
                    "rolling_mean_7": mean_7,
                    "rolling_std_7": std_7,
                    "rolling_mean_14": mean_14,
                    "rolling_std_14": std_14,
                    "dayofweek": target_time.dayofweek,
                    "month": target_time.month,
                    "day": target_time.day,
                    "is_weekend": int(target_time.dayofweek >= 5),
                })
                y_vals.append(row_val[target_col])

    X = pd.DataFrame(rows)
    y = np.array(y_vals) if y_vals else None
    return X, y


class DirectLGBMForecaster:
    """Global LightGBM model across all series using direct multi-horizon forecasting."""

    def __init__(self, horizon: int, params: dict | None = None):
        self.horizon = horizon
        self.params = params or {}
        self.encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
        self.model = None

    def fit(self, X_train: pd.DataFrame, y_train: np.ndarray, X_val: pd.DataFrame | None = None, y_val: np.ndarray | None = None):
        if len(X_train) == 0 or lgb is None:
            return self

        X_tr = X_train.copy()
        X_tr["__series"] = self.encoder.fit_transform(X_tr[["__series"]]).astype(int)

        lgb_params = {
            "objective": "regression_l1",
            "n_estimators": 200,
            "learning_rate": 0.05,
            "num_leaves": 31,
            "random_state": SEED,
            "n_jobs": N_JOBS,
            "verbose": -1,
        }
        for k, v in self.params.items():
            if k in lgb_params or k in ("max_depth", "min_child_samples", "subsample", "colsample_bytree"):
                lgb_params[k] = v

        self.model = lgb.LGBMRegressor(**lgb_params)
        eval_set = None
        if X_val is not None and y_val is not None and len(X_val) > 0:
            X_v = X_val.copy()
            X_v["__series"] = self.encoder.transform(X_v[["__series"]]).astype(int)
            eval_set = [(X_v, y_val)]

        self.model.fit(
            X_tr,
            y_train,
            eval_set=eval_set,
            callbacks=[lgb.early_stopping(stopping_rounds=15, verbose=False)] if eval_set else None,
        )
        return self

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        if self.model is None or len(X) == 0:
            return np.zeros(len(X))
        X_test = X.copy()
        s_col = next(
            (c for c in ("__series", "store_id", "store", "series_id", "id") if c in X_test.columns),
            None,
        )
        if s_col and s_col != "__series":
            X_test["__series"] = X_test[s_col].astype(str)
        elif "__series" not in X_test.columns:
            X_test["__series"] = "series_0"

        try:
            X_test["__series"] = self.encoder.transform(X_test[["__series"]]).astype(int)
        except Exception:
            X_test["__series"] = 0

        time_cols = [c for c in ("date", "timestamp", "datetime", "__dt") if c in X_test.columns]
        if time_cols:
            dt = pd.to_datetime(X_test[time_cols[0]], errors="coerce")
            X_test["dayofweek"] = dt.dt.dayofweek.fillna(0).astype(int)
            X_test["month"] = dt.dt.month.fillna(1).astype(int)
            X_test["day"] = dt.dt.day.fillna(1).astype(int)
            X_test["is_weekend"] = (X_test["dayofweek"] >= 5).astype(int)

        feature_names = getattr(self.model, "feature_name_", [])
        for f in feature_names:
            if f not in X_test.columns:
                X_test[f] = 1.0 if f == "horizon_step" else 0.0

        if feature_names:
            X_test = X_test[feature_names]

        return np.asarray(self.model.predict(X_test)).ravel()


def main():
    t0 = time.time()
    progress("load_data", message="Loading time-series data")

    pdf, time_col, series_cols = load_dataset()
    target_col = CONFIG["target"]
    eval_split_name = CONFIG.get("eval_split", "test")
    season_len = get_seasonality(FREQ)

    train_mask = pdf["__split"] == SPLIT_IDS["train"]
    # Handle fidelity_rows via suffix-window __r
    fidelity_rows = CONFIG.get("fidelity_rows")
    if fidelity_rows and train_mask.sum() > fidelity_rows:
        n_train = train_mask.sum()
        train_mask = train_mask & (pdf["__r"] < fidelity_rows / n_train)

    train_df = pdf[train_mask].copy().reset_index(drop=True)
    val_df = pdf[pdf["__split"] == SPLIT_IDS["valid"]].copy().reset_index(drop=True)
    test_df = pdf[pdf["__split"] == SPLIT_IDS["test"]].copy().reset_index(drop=True)

    eval_df = val_df if eval_split_name == "valid" else test_df
    # History before the eval split
    eval_hist_df = train_df if eval_split_name == "valid" else pd.concat([train_df, val_df], ignore_index=True)

    progress("baselines", message="Running seasonal-naive and ETS floor baselines")

    # 1. Seasonal Naive baseline
    s_naive = SeasonalNaiveModel(season_length=season_len).fit(eval_hist_df, target_col)
    eval_series = eval_df["__series"].to_list()
    eval_steps = [(i % HORIZON) + 1 for i in range(len(eval_df))]
    s_naive_preds = s_naive.predict(eval_series, eval_steps)
    s_naive_metrics = compute_metrics(eval_df[target_col].to_numpy(), s_naive_preds)

    # 2. ETS baseline
    ets_model = ETSModel(season_length=season_len).fit(eval_hist_df, target_col)
    ets_preds = ets_model.predict(eval_series, eval_steps)
    ets_metrics = compute_metrics(eval_df[target_col].to_numpy(), ets_preds)

    baseline_scores = {
        "seasonal_naive": s_naive_metrics["smape"],
        "ets": ets_metrics["smape"],
    }

    # 3. Model family choice
    family = CONFIG.get("model_family", "lightgbm")
    progress("train_model", family=family)

    if family == "seasonal_naive":
        active_model = s_naive
        y_eval_pred = s_naive_preds
    elif family == "ets":
        active_model = ets_model
        y_eval_pred = ets_preds
    else:
        # Default: Global LightGBM forecaster
        X_train, y_train = build_direct_features(train_df, target_col, HORIZON, is_training=True)
        X_val, y_val = build_direct_features(val_df, target_col, HORIZON, is_training=False, origin_df=train_df)
        X_eval, y_eval = build_direct_features(eval_df, target_col, HORIZON, is_training=False, origin_df=eval_hist_df)

        lgbm_forecaster = DirectLGBMForecaster(horizon=HORIZON, params=CONFIG.get("hyperparameters", {}))
        lgbm_forecaster.fit(X_train, y_train, X_val, y_val)
        active_model = lgbm_forecaster
        y_eval_pred = lgbm_forecaster.predict(X_eval)

    final_metrics = compute_metrics(eval_df[target_col].to_numpy(), y_eval_pred)
    primary_metric = CONFIG.get("metric", "smape").lower()
    score = final_metrics.get(primary_metric, final_metrics["smape"])

    # Determine if winner beats seasonal-naive baseline
    s_naive_baseline_score = s_naive_metrics.get(primary_metric, s_naive_metrics["smape"])
    if family == "seasonal_naive":
        beats_seasonal_naive = True
    else:
        beats_seasonal_naive = bool(score < s_naive_baseline_score)

    train_time = round(time.time() - t0, 3)

    metrics_out = {
        "score": score,
        "primary_metric": primary_metric,
        "metrics": final_metrics,
        "baseline_scores": baseline_scores,
        "beats_seasonal_naive": beats_seasonal_naive,
        "seasonal_naive_score": s_naive_baseline_score,
        "train_time_s": train_time,
        "horizon": HORIZON,
        "frequency": FREQ,
        "model_family": family,
    }

    Path("metrics.json").write_text(json.dumps(metrics_out, indent=2), encoding="utf-8")
    progress("metrics_written", score=score, beats_seasonal_naive=beats_seasonal_naive)

    if CONFIG.get("save_model", True):
        user_features = [*series_cols, "horizon_step"] if series_cols else [time_col, "horizon_step"]
        if not user_features:
            user_features = ["horizon_step"]
        bundle_dict = {
            "model": active_model,
            "task_type": "time_series_forecasting",
            "target": target_col,
            "features": user_features,
            "time_column": time_col,
            "series_id_columns": series_cols,
            "horizon": HORIZON,
            "frequency": FREQ,
            "drop_columns": CONFIG.get("drop_columns", []),
            "dtypes": {f: "numeric" if f == "horizon_step" else "category" for f in user_features},
            "categories": {
                col: [str(c) for c in eval_df[col].dropna().unique().tolist()]
                for col in series_cols
                if col in eval_df.columns
            },
            "config": CONFIG,
        }
        joblib.dump(bundle_dict, "model.joblib")
        progress("model_saved")


if __name__ == "__main__":
    main()
